# Sample config for Prometheus.

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: prometheus-node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['10.0.0.102:9100', '10.0.0.103:9100']

#  - job_name: 'my_dummy_exporter'
#    scrape_interval: 5s
#    metrics_path: ''
#    static_configs:
#      - targets: ['dummy_exporter1:65433', 'dummy_exporter2:65433']
  - job_name: dummy
    consul_sd_configs:
      - server: '10.0.0.109:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,dummy,.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job
