---

#- name: Install node-exporter
#  apt:
#    name: prometheus-node-exporter
#    update_cache: yes
#  notify: restart node-exporter

- name: Install node-exporter
  copy:
    src: node_exporter
    dest: /usr/bin/node-exporter
    mode: 0755

- name: Start node-exporter
  shell: nohup /usr/bin/node-exporter &
