---

- name: Enable elasticsearch service
  service: name=elasticsearch enabled=yes
  notify: Restart elasticsearch

#- name: Copy elasticsearch defaults
#  template: src=etc/default/elasticsearch dest=/etc/default/elasticsearch
#  notify: Restart elasticsearch

- name: Create elasticsearch data dir
  file: name=/data/elasticsearch state=directory recurse=yes owner=elasticsearch
  notify: Restart elasticsearch

- name: Copy elasticsearch config
  template: src=etc/elasticsearch/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: Restart elasticsearch
